Reduce redundant usage of the compatibility module
pika/pika pull request #1441
Opened 2023-08-03 21:20 UTC by alfawal

## Proposed Changes

Reducing the usage of the `pika.compat` usage. It's really depressing for a first-time contributor to see Python 2 being used nowadays.

I believe/hope that these changes will encourage more people to contribute!

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes issue #NNNN)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [x] Cosmetics (whitespace, appearance)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after
creating the PR. If you're unsure about any of them, don't hesitate to
ask on the
[`pika-python`](https://groups.google.com/forum/#!forum/pika-python)
mailing list. We're here to help! This is simply a reminder of what we
are going to look for before merging your code._

- [x] I have read the `CONTRIBUTING.md` document
- [ ] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further Comments

On the consistency side. I believe that this repository should:
- Add pre-commit config and inform the contributors to use it. The pre-commit config:
    - Use `black` as its formatter.
    - Use `isort` as its imports reordering handler.
    - (Optional) Use items from `ruff`.
    - (Optional) Use `pydocstyle` for docstrings with the Google style.
    - etc.
- Do an initial run with the pre-commit on all files.

2023-08-03 21:29 UTC, alfawal commented
What is the status of the file `utils/codegen.py`? it runs on Python 2 only, should I remove it? is it just a normal file deletion or is there anything that I have to do?

2023-08-03 22:35 UTC, lukebakken requested changes
Thanks for this contribution. Please note that these changes have broken the test suites! I will leave this PR as a draft until the tests are fixed. Thanks.

2024-07-01 23:15 UTC, lukebakken commented
@alfawal we'll leave `utils/codegen.py` as-is. It generates `pika/spec.py`. If we ever have to run `codegen.py` again, we'll update it for Python 3 at that time.

2024-07-01 23:51 UTC, lukebakken approved these changes
Thanks!

2024-07-01 23:51 UTC, merged