Add an asynchronous reconnecting consumer example with exponential backoff for robust RabbitMQ reconnection handling
pika/pika pull request #1497
Opened 2024-12-02 14:51 UTC by mullachv

## Proposed Changes

This pull request introduces an asynchronous reconnecting consumer for RabbitMQ, which implements a robust reconnection logic using exponential backoff. This feature is particularly helpful for server-side services that need to maintain a persistent connection to RabbitMQ but face interruptions due to network errors, server unavailability, or other transient issues.

The proposed changes include:

A new AsyncReconnectingConsumer class that uses asyncio to handle RabbitMQ connection failures and retries with progressive backoff and jitter.
Unit tests to verify the reconnection logic, including retries after failures and successful connection restoration.
Google-style formatting for all new code, adhering to Pika's contribution guidelines.

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes issue #NNNN)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after
creating the PR. If you're unsure about any of them, don't hesitate to
ask on the
[`pika-python`](https://groups.google.com/forum/#!forum/pika-python)
mailing list. We're here to help! This is simply a reminder of what we
are going to look for before merging your code._

- [x] I have read the `CONTRIBUTING.md` document
- [x] All tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

## Further Comments

The addition of the asynchronous reconnecting consumer is motivated by the need for a robust RabbitMQ client that can handle unexpected connection disruptions. This is particularly useful in server-side services where RabbitMQ is a critical component for messaging and any downtime can lead to cascading failures across dependent systems.

The proposed solution includes:

Asynchronous Reconnection with Exponential Backoff: Ensures that reconnection attempts are not overly aggressive and adapt dynamically to network or server conditions.
Compatibility with Existing Codebase: The implementation leverages existing Pika conventions and integrates seamlessly with the event-driven architecture of RabbitMQ.
Test Coverage: Comprehensive unit tests ensure the feature works as intended and is robust against edge cases.

2024-12-03 17:02 UTC, lukebakken commented
Thank you, I will review this when I have time. I'm very busy providing support for commercial RabbitMQ users.

2024-12-04 02:03 UTC, mullachv commented
@lukebakken Thank you. Let me know if you have any code review comments

2025-01-07 02:42 UTC, mullachv commented
@lukebakken Is anything required from my end at this time on this pull request?

2025-01-07 02:43 UTC, lukebakken commented
Nope, I just haven't had time to review this.

2025-01-20 09:36 UTC, mullachv commented
@lukebakken A friendly nudge to request review and run build checks

2025-01-21 16:28 UTC, lukebakken requested changes
Rather than have a totally new example, I would prefer that the reconnection logic be added to the existing async publisher and consumer example code.

2025-01-21 16:31 UTC, lukebakken commented
@mullachv I appreciate your efforts here, but please remember that this software, and probably almost everything you use day-to-day, is _free_. Nudging project maintainers is generally considered rude, especially when those maintainers are busy with higher priority work, or busy supporting customers who _pay_ for their software.

2025-05-06 15:33 UTC, lukebakken commented
Thank you, I will review this when I have time.

2025-06-17 14:23 UTC, lukebakken commented
@mullachv it looks as though you ran the code through an auto formatter. Could you please undo formatting changes and just include your code changes?

2025-06-17 14:35 UTC, lukebakken requested changes
Please undo formatting-only changes.

2026-02-22 01:25 UTC, mullachv commented
@lukebakken 
Reverted formatting-only changes (single quotes, original line breaks) and kept only the reconnecting consumer changes. Fixed main() to use RobustReconnectingConsumer. Ready for another look.

2026-05-01 22:25 UTC, lukebakken commented
@mullachv thank you for the time and effort you put into this PR. Reconnection resilience is an important topic and I appreciate you working on it.

After reviewing the current state of the code, I've decided to close this PR. The existing `ReconnectingExampleConsumer` in the example file already handles reconnection with exponential backoff, and the changes here introduce some design issues that would require a substantial rewrite to resolve -- at which point it would effectively be new code rather than your contribution.

A few specifics in case they're helpful for future work:

- `time.sleep()` inside the reconnect path blocks the `SelectConnection` ioloop, which prevents it from processing any I/O during the backoff wait
- The `asyncio.Event` objects are never awaited, so they function as plain booleans rather than providing async coordination
- The `run()` method and outer `ReconnectingExampleConsumer` class were removed, so the example has no entry point that starts the ioloop

If you'd like to contribute improvements to the existing reconnecting consumer example (e.g., adding jitter to the backoff), a smaller targeted PR would be welcome. Thanks again for your interest in pika.

2026-05-01 22:25 UTC, closed without merging